# Generated by Django 3.2.7 on 2021-10-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=128)),
                ('author', models.CharField(default='author', max_length=128)),
                ('content', models.TextField(default='content', max_length=10000)),
                ('posted', models.DateTimeField(verbose_name='date published')),
                ('commentNumber', models.CharField(default="0", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(default=0, max_length=128)),
                ('who', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(default='commenter', max_length=128)),
                ('email', models.EmailField(default='email@email.com', max_length=128)),
                ('content', models.TextField(default='content', max_length=10000)),
                ('posted', models.DateTimeField(verbose_name='date published')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
